server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongouser
      password: mongopassword
      database: UserProfileDB
  cloud:
    config:
      import-check:
        enabled: false